import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ELEMENT_LIST } from './elements.js';
import { PhoenixCard, type PhoenixNft } from './phoenix-card.js';
import type { KlingModelId } from './kling-models.js';
import styles from './phoenix-studio.module.css';

const DEFAULT_API_KEY = ''; // set your OpenRouter key in the UI

export type PhoenixStudioProps = {
  apiKey:string; onApiKeyChange:(k:string)=>void; nfts:PhoenixNft[]; minting:boolean;
  onMint:()=>void; onAnimate:(id:string,modelId:KlingModelId)=>void;
  onAttachJobId:(nftId:string,jobId:string)=>Promise<void>|void;
  onImportFromJobId:(jobId:string)=>Promise<void>|void;
  onDelete:(id:string)=>Promise<void>|void;
};

export function PhoenixStudio({ apiKey,onApiKeyChange,nfts,minting,onMint,onAnimate,onAttachJobId,onImportFromJobId,onDelete }: PhoenixStudioProps) {
  const [_d]=useState(DEFAULT_API_KEY); void _d;
  const recent=nfts.slice(0,6);
  return (
    <div className={styles.app}>
      <header className={styles.header}>
        <div className={styles.brand}><span className={styles.logo}>🔥</span><div><h1>Phoenix Forge</h1><p>Unique elemental Phoenix NFTs · Generated by Gemini · Animated by Kling</p></div></div>
        <div className={styles.headerRight}>
          <Link to="/collection" className={styles.collectionLink}>📜 Collection ({nfts.length})</Link>
          <div className={styles.keyRow}>
            <label htmlFor="key">OpenRouter API Key</label>
            <input id="key" type="password" value={apiKey} onChange={e=>onApiKeyChange(e.target.value)} placeholder="sk-or-v1-…"/>
          </div>
        </div>
      </header>
      <section className={styles.heroPanel}>
        <div className={styles.heroLeft}>
          <h2>Forge a unique Phoenix from the 7 sacred elements</h2>
          <p>Every Phoenix is born from a random combination of elemental forces: 5 natural — Acqua, Terra, Fuoco, Fulmine, Aria — and 2 cosmic — Luce & Ombra. Each NFT is one of a kind.</p>
          <div className={styles.elementGrid}>
            {ELEMENT_LIST.map(e=>(
              <div key={e.id} className={styles.elementChip} style={{ background:`radial-gradient(circle at 30% 30%,${e.glow},transparent 70%)`, borderColor:e.color }}>
                <span className={styles.elementEmoji}>{e.emoji}</span><span>{e.name}</span>
              </div>
            ))}
          </div>
          <div className={styles.mintRow}>
            <button type="button" className={styles.mintBtn} onClick={onMint} disabled={minting||!apiKey}>{minting?'🔥 Forging…':'✨ Mint a unique Phoenix'}</button>
            <button type="button" className={styles.importBtn} disabled={!apiKey} onClick={async()=>{ const jobId=window.prompt('OpenRouter video job_id:'); if(!jobId) return; try{await onImportFromJobId(jobId.trim());}catch(e){window.alert(`Error: ${e instanceof Error?e.message:e}`);} }}>🔗 Import from Job ID</button>
          </div>
        </div>
        <div className={styles.heroRight} aria-hidden><div className={styles.orb}><div className={styles.orbInner}/></div></div>
      </section>
      <section className={styles.collection}>
        <div className={styles.collectionHeader}>
          <h2>Recent forge</h2>
          {nfts.length>6&&<Link to="/collection" className={styles.viewAll}>View all {nfts.length} →</Link>}
        </div>
        {recent.length===0?<div className={styles.empty}>No phoenixes yet. Press <strong>Mint</strong> to forge your first one.</div>:(
          <div className={styles.grid}>{recent.map(n=><PhoenixCard key={n.id} nft={n} onAnimate={onAnimate} onAttachJobId={onAttachJobId} onDelete={onDelete}/>)}</div>
        )}
      </section>
      <footer className={styles.footer}>Built with OpenRouter · Gemini 2.5 Flash Image · Kling Video O1</footer>
    </div>
  );
}
